#!/usr/bin/env python3
"""Regenerate src/ruby/node_tag.rs from ruby-prism's own Node enum.

    cargo build && script/gen-node-tag.py

The tag is the variant name, because it is an **on-disk format**: a norm_hash
keys an LLM summary that cost real money, and any tagging scheme derived from
declaration order would renumber every node the day Prism adds one.

The generated match is deliberately exhaustive — no catch-all. A Prism upgrade
that adds a node breaks the build here, which is the alarm rwr's vendored
`generated.rs` does not have (its three `_ =>` arms would silently hand back
an empty child list instead).
"""
import glob, os, re, sys

roots = glob.glob('target/*/build/ruby-prism-*/out/bindings.rs')
if not roots:
    sys.exit('no ruby-prism bindings found; run `cargo build` first')
src = open(max(roots, key=os.path.getmtime)).read()
enum = src[src.index('pub enum Node<'):]
enum = enum[:enum.index('\n}\n')]
names = re.findall(r'^    ([A-Z][A-Za-z0-9]*Node) \{', enum, re.M)
assert len(names) > 100, names

arms = '\n'.join(f'        Node::{n} {{ .. }} => "{n}",' for n in names)
open('src/ruby/node_tag.rs', 'w').write(f'''//! GENERATED by script/gen-node-tag.py -- do not edit by hand.
//!
//! A stable name for every Prism node variant. `std::mem::discriminant` cannot
//! serve: it has no portable value, and a `norm_hash` is an on-disk key for an
//! LLM summary that cost real money.
//!
//! Exhaustive on purpose. A Prism upgrade that adds a node breaks the build
//! here rather than silently changing what hashes to what.

use ruby_prism::Node;

/// The variant's own name. Hashing {len(names)} distinct strings costs a few
/// bytes per node; an integer table would be faster and would renumber every
/// node the day Prism adds one.
pub(crate) fn tag(node: &Node<'_>) -> &'static str {{
    match node {{
{arms}
    }}
}}
''')
print(f'wrote src/ruby/node_tag.rs ({len(names)} variants)')
