//! Summaries handed to contour by the sessions that use it.
//!
//! The write path for **organic, incremental indexing** (DEC-018): a session
//! that has just read and understood a method contributes what it learned
//! before moving on, so the index gets better every time somebody works in the
//! repository rather than only when somebody pays for a bulk fill.
//!
//! DEC-016's rules apply here in full. A contributed summary is not free — it
//! cost a session's tokens and a person's attention — so it is written to the
//! purchased half, survives every reindex, and is keyed with the same care.
//!
//! Three gates, in this order, and each of them rejects rather than repairs:
//!
//! 1. **The declared prompt version must be the one this server speaks.** The
//!    template lives in the skill, so a stale skill would otherwise contribute
//!    answers of a different shape under a current key. Required, not
//!    defaulted: defaulting is precisely how the key would come to lie.
//! 2. **The unit's body must still hash to what the index recorded.** The M3
//!    stale-slice guard, pointed the other way — there it stopped contour
//!    summarizing the wrong lines, here it stops a session attributing a
//!    summary to a method that has since changed underneath it.
//! 3. **The payload must match the schema the API path uses.** Unknown fields,
//!    empty required strings, and side effects outside the closed vocabulary
//!    are all refused with a message the session can act on. Coercing would
//!    put a quietly wrong summary into a store that never forgets.

use super::{SideEffect, Summary};
use crate::store::{Store, SummaryKey, VIA_MCP};
use anyhow::{Result, bail};
use serde_json::Value;
use std::path::Path;

/// The shape contributed summaries are expected in.
///
/// Separate from the API path's version because it is a different artifact —
/// that one lives in `super::prompt`, this one lives in the skill a session
/// reads. They move independently, so they key independently.
pub const CONTRIBUTED_PROMPT_VERSION: &str = "mcp-v1";

/// The fields a summary must carry, and nothing else.
const REQUIRED: [&str; 6] = [
    "summary",
    "primary_purpose",
    "secondary_concerns",
    "side_effects",
    "domain",
    "patterns",
];

/// The closed side-effect vocabulary, spelled out here so a rejection can name
/// what was allowed.
const SIDE_EFFECTS: [&str; 7] = [
    "persists",
    "network",
    "filesystem",
    "mutates",
    "observes",
    "raises",
    "spawns",
];

/// What was stored, echoed back so a session can confirm what it bought.
#[derive(Debug, serde::Serialize)]
pub struct Accepted {
    pub id: String,
    pub path: String,
    pub model: String,
    pub via: &'static str,
    pub prompt_version: String,
}

/// Validate a contributed summary and store it.
pub fn store(
    store: &mut Store,
    root: &Path,
    unit_id: &str,
    path_hint: Option<&str>,
    model: &str,
    prompt_version: &str,
    payload: &Value,
) -> Result<Accepted> {
    if prompt_version != CONTRIBUTED_PROMPT_VERSION {
        bail!(
            "this contour speaks prompt version `{CONTRIBUTED_PROMPT_VERSION}`, not \
             `{prompt_version}`. Use the template from the current contour skill, and \
             declare its version."
        );
    }
    if model.trim().is_empty() {
        bail!(
            "`model` is required: a summary that does not say which model wrote it cannot be kept apart from one that does"
        );
    }

    let root_str = root.to_string_lossy().into_owned();
    let mut matches: Vec<crate::store::Located> = store
        .units(&root_str)?
        .into_iter()
        .filter(|l| l.unit.id() == unit_id)
        .filter(|l| path_hint.is_none_or(|p| l.path == p))
        .collect();
    if matches.is_empty() {
        bail!("no unit named `{unit_id}` in this checkout — index it first, or check the name");
    }
    // Ambiguity is refused rather than guessed at: a Rust free function's name
    // is not unique across files (see `rust`'s known limit), and silently
    // attributing a summary to the wrong one is unrecoverable.
    if matches.len() > 1 {
        let where_ = matches
            .iter()
            .map(|l| format!("{}:{}", l.path, l.unit.line))
            .collect::<Vec<_>>()
            .join(", ");
        bail!("`{unit_id}` is ambiguous in this checkout ({where_}); pass `path` to choose one");
    }
    let located = matches.remove(0);
    let Some(norm_hash) = located.unit.norm_hash else {
        bail!(
            "`{unit_id}` has no body to summarize (it is generated by `{}`)",
            located.unit.via.as_deref().unwrap_or("a macro")
        );
    };

    // Gate 2, before validating the payload: if the body moved, the summary is
    // about something else and no amount of well-formedness saves it.
    super::fill::slice(
        root,
        &located.path,
        located.unit.line,
        located.unit.end_line,
        norm_hash,
    )?;

    let summary = validate(payload)?;
    let ctx_hash = super::Context::of(&located.unit).hash();
    store.put_summary(
        &SummaryKey {
            norm_hash,
            ctx_hash,
            prompt: CONTRIBUTED_PROMPT_VERSION,
            model,
            via: VIA_MCP,
        },
        &summary,
    )?;
    Ok(Accepted {
        id: located.unit.id(),
        path: located.path,
        model: model.to_string(),
        via: VIA_MCP,
        prompt_version: CONTRIBUTED_PROMPT_VERSION.to_string(),
    })
}

/// Check a payload against the schema the API path is constrained to, and
/// refuse anything that does not fit.
///
/// Deliberately stricter than reading a stored summary. `SideEffect` has an
/// `Other` fallback so a paid API answer is never lost to one invented word;
/// a contribution has no such excuse, because the session can be told the
/// vocabulary and try again. Liberal in what we accept from our own storage,
/// strict in what we accept from outside.
pub fn validate(payload: &Value) -> Result<Summary> {
    let Some(object) = payload.as_object() else {
        bail!(
            "expected a JSON object with fields: {}",
            REQUIRED.join(", ")
        );
    };
    for field in REQUIRED {
        if !object.contains_key(field) {
            bail!("missing required field `{field}`");
        }
    }
    let unknown: Vec<&str> = object
        .keys()
        .map(String::as_str)
        .filter(|k| !REQUIRED.contains(k))
        .collect();
    if !unknown.is_empty() {
        bail!(
            "unexpected field(s) {}; the schema is exactly: {}",
            unknown.join(", "),
            REQUIRED.join(", ")
        );
    }
    for effect in object["side_effects"].as_array().unwrap_or(&Vec::new()) {
        let Some(name) = effect.as_str() else {
            bail!("`side_effects` must be strings");
        };
        if !SIDE_EFFECTS.contains(&name) {
            bail!(
                "`{name}` is not a side effect contour knows; use any of: {}",
                SIDE_EFFECTS.join(", ")
            );
        }
    }

    let summary: Summary = serde_json::from_value(payload.clone())
        .map_err(|err| anyhow::anyhow!("payload does not match the summary schema: {err}"))?;
    for (field, value) in [
        ("summary", &summary.summary),
        ("primary_purpose", &summary.primary_purpose),
        ("domain", &summary.domain),
    ] {
        if value.trim().is_empty() {
            bail!("`{field}` must not be empty");
        }
    }
    // Unreachable given the vocabulary check above, and asserted anyway: it is
    // the one way a coercion could still slip through.
    if summary.side_effects.contains(&SideEffect::Other) {
        bail!("`side_effects` fell back to `other`, which a contribution may not do");
    }
    Ok(summary)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn good() -> Value {
        serde_json::json!({
            "summary": "Returns a customer's unpaid invoices, oldest first.",
            "primary_purpose": "unpaid invoice lookup",
            "secondary_concerns": ["ordering"],
            "side_effects": ["persists"],
            "domain": "billing",
            "patterns": ["scope"]
        })
    }

    #[test]
    fn accepts_the_shape_the_api_path_produces() {
        let summary = validate(&good()).unwrap();
        assert_eq!(summary.domain, "billing");
        assert_eq!(summary.side_effects, [SideEffect::Persists]);
    }

    /// Each of these is a way a session could hand over something plausible
    /// and wrong. All are refused with a message naming the fix.
    #[test]
    fn rejects_rather_than_repairs() {
        /// A way a session could hand over something plausible and wrong.
        type Case = (&'static str, fn(&mut Value), &'static str);
        let cases: [Case; 5] = [
            (
                "a missing field",
                |v: &mut Value| {
                    v.as_object_mut().unwrap().remove("domain");
                },
                "missing required field",
            ),
            (
                "an invented field",
                |v: &mut Value| v["confidence"] = serde_json::json!(0.9),
                "unexpected field",
            ),
            (
                "an invented side effect",
                |v: &mut Value| v["side_effects"] = serde_json::json!(["teleports"]),
                "not a side effect contour knows",
            ),
            (
                "an empty summary",
                |v: &mut Value| v["summary"] = serde_json::json!("   "),
                "must not be empty",
            ),
            (
                "a wrong type",
                |v: &mut Value| v["patterns"] = serde_json::json!("scope"),
                "does not match the summary schema",
            ),
        ];
        for (label, mutate, expected) in cases {
            let mut payload = good();
            mutate(&mut payload);
            let err = validate(&payload)
                .expect_err(&format!("{label} should be refused"))
                .to_string();
            assert!(err.contains(expected), "{label}: got `{err}`");
        }
    }

    /// The API path keeps `other` so a paid answer survives one odd word; a
    /// contribution does not, because the session can simply be told.
    #[test]
    fn the_contribution_path_is_stricter_than_the_storage_type() {
        let stored: Summary = serde_json::from_str(
            r#"{"summary":"s","primary_purpose":"p","domain":"d","side_effects":["teleports"]}"#,
        )
        .expect("storage stays permissive");
        assert_eq!(stored.side_effects, [SideEffect::Other]);
    }
}
